#!/usr/bin/env bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/functions.sh"
output="${Red}No instance supplied, use '\*' to delete all instances on the account, use -f to force delete and avoid confirmation prompts${Color_Off}" 

if [ -z "$1" ]
then
	echo -e "$output"
	exit
fi

force="false"
query=""
instance_names=""

for var in "$@"; do
	if [ "$var" == "-f" ]; then
		force=true
	else
		query="$query $var"
	fi
done

instance_names=$(query_instances $query)

if [[ "$instance_names" ]]
then
delete_instances "$instance_names" "$force"
else
        >&2 echo -e "$output ${Color_Off}"
       exit
fi

