#!/usr/bin/env bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/functions.sh"
current=$(readlink -f "$AXIOM_PATH/axiom.json" | rev | cut -d / -f 1 | rev | cut -d . -f 1)
echo -e "Listing instances in account: $(echo $current)" | perl -pe '$_ = "\033[1;37m$_\033[1;32m" if($. % 2)'


if [ -z $1 ]; then

instance_pretty |  perl -pe '$_ = "\033[1;37m$_\033[0m" if($. % 2); $_ = "\033[1;32m$_\033[0m" unless ($. % 2)'

else
	if [[ "$1" == "--json" ]]; then
		instances
	elif [[ "$1" == "--list" ]]; then
		instance_list
	elif [[ "$1" == "--appliance" ]]; then
		pretty_appliances
	else
		resp=$(query_instances "$1")
		count=$(echo $resp | tr ' ' '\n' | wc -l | awk '{ print $1 }')

		if [[ "$count" -gt 1 ]]; then
			i=1
			for name in $resp; do
				echo "$i:$name"
				i=$((i + 1))
			done
		else
			instance_ip "$1"
		fi
	fi
fi
